import type { Metadata } from 'next';

import { notFound } from 'next/navigation';

import { cache } from 'react';

import { PortfolioProjectDetail } from '@/features/portfolio/components/PortfolioProjectDetail';

import { getPortfolioProject } from '@/features/portfolio/server/get-portfolio-project';

/* =========================================================
   ROUTE CONFIGURATION
   ========================================================= */

export const revalidate = 300;

/* =========================================================
   ROUTE CONTRACT
   ========================================================= */

/**
 * Next.js App Router dynamic params are asynchronous.
 *
 * We define this locally instead of relying on
 * PageProps<'/portfolio/[slug]'> because AppRoutes is
 * generated by Next.js and may not contain a newly-created
 * route until route type generation has completed.
 */
type PortfolioProjectPageProps = {
  params: Promise<{
    slug: string;
  }>;
};

/* =========================================================
   REQUEST-LOCAL PROJECT CACHE
   ========================================================= */

/**
 * generateMetadata() and the page itself both request
 * the same portfolio project.
 *
 * React cache deduplicates that work within the render.
 */
const getCachedPortfolioProject = cache(getPortfolioProject);

/* =========================================================
   URL SAFETY
   ========================================================= */

function getSafeAbsoluteUrl(value: string | null | undefined) {
  if (!value) {
    return null;
  }

  try {
    const url = new URL(value);

    if (url.protocol !== 'https:' && url.protocol !== 'http:') {
      return null;
    }

    return url.toString();
  } catch {
    return null;
  }
}

/* =========================================================
   METADATA
   ========================================================= */

export async function generateMetadata({ params }: PortfolioProjectPageProps): Promise<Metadata> {
  const { slug } = await params;

  const project = await getCachedPortfolioProject(slug);

  if (!project) {
    return {
      title: 'Project not found',

      robots: {
        index: false,
        follow: false
      }
    };
  }

  const seo = project.seo;

  const title = seo?.title ?? project.name;

  const description =
    seo?.description ?? project.summary ?? project.tagline ?? project.description ?? undefined;

  const canonicalUrl = getSafeAbsoluteUrl(seo?.canonicalUrl);

  const ogImage = getSafeAbsoluteUrl(seo?.ogImage);

  const robots = seo?.robots;

  const index = robots !== 'NOINDEX_FOLLOW' && robots !== 'NOINDEX_NOFOLLOW';

  const follow = robots !== 'INDEX_NOFOLLOW' && robots !== 'NOINDEX_NOFOLLOW';

  return {
    title,

    description,

    keywords: seo?.keywords ?? undefined,

    alternates: canonicalUrl
      ? {
          canonical: canonicalUrl
        }
      : undefined,

    robots: {
      index,
      follow
    },

    openGraph: {
      type: 'website',

      title: seo?.ogTitle ?? title,

      description: seo?.ogDescription ?? description,

      images: ogImage
        ? [
            {
              url: ogImage
            }
          ]
        : undefined
    }
  };
}

/* =========================================================
   PAGE
   ========================================================= */

export default async function PortfolioProjectPage({ params }: PortfolioProjectPageProps) {
  const { slug } = await params;

  const project = await getCachedPortfolioProject(slug);

  if (!project) {
    notFound();
  }

  return <PortfolioProjectDetail project={project} />;
}
